services:
  # 1. Bancos de Dados Isolados
  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_auth
    networks:
      - rede-microsservicos

  postgres-academic:
    image: postgres:15-alpine
    container_name: postgres-academic
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_academic
    networks:
      - rede-microsservicos

  postgres-assignment:
    image: postgres:15-alpine
    container_name: postgres-assignment
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_assignment
    networks:
      - rede-microsservicos

  # 2. Microsserviço de Autenticação
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      DB_HOST: postgres-auth
      SERVER_PORT: 8080 # <-- Adicionado
    depends_on:
      - postgres-auth
    networks:
      - rede-microsservicos

  # 3. Microsserviço Acadêmico
  academic-service:
    build:
      context: ../services/academic-service
      dockerfile: Dockerfile
    container_name: academic-service
    ports:
      - "8082:8080"
    environment:
      DB_HOST: postgres-academic
      SERVER_PORT: 8080 # <-- Adicionado
    depends_on:
      - postgres-academic
    networks:
      - rede-microsservicos

  # 4. Microsserviço de Atividades
  assignment-service:
    build:
      context: ../services/assignment-service
      dockerfile: Dockerfile
    container_name: assignment-service
    ports:
      - "8083:8080"
    environment:
      DB_HOST: postgres-assignment
      ACADEMIC_SERVICE_URL: http://academic-service:8080
      SERVER_PORT: 8080 # <-- Adicionado
    depends_on:
      - postgres-assignment
      - academic-service
    networks:
      - rede-microsservicos

networks:
  rede-microsservicos:
    driver: bridge
