name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-analyze:
    name: Validar ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [academic-service, assignment-service]

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Tornar o Maven Wrapper executável
      working-directory: services/${{ matrix.service }}
      run: chmod +x mvnw

    - name: Executar Testes Unitários
      working-directory: services/${{ matrix.service }}
      run: ./mvnw clean test

    - name: Lint e Análise Estática (PMD)
      working-directory: services/${{ matrix.service }}
      run: ./mvnw org.apache.maven.plugins:maven-pmd-plugin:3.21.2:check -DfailOnViolation=false

    - name: Verificação de Segurança (Trivy Scanner)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'services/${{ matrix.service }}'
        format: 'table'
        exit-code: '1' # Falha o build se encontrar vulnerabilidades críticas
        ignore-unfixed: true
        severity: 'CRITICAL'

  build-auth-service:
    name: Compilar auth-service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build do Auth Service
      working-directory: services/auth-service
      run: mvn clean compile
